# Generated by Django 5.0.3 on 2024-04-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0003_customers_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
