# Generated by Django 5.0.3 on 2024-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0011_alter_bookride_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookride',
            name='ride_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ride accepted', 'Ride Accepted'), ('in_progress', 'In Progress'), ('ride ended', 'Ride Ended'), ('ride cancelled', 'Ride Cancelled')], default='waiting', max_length=20),
        ),
    ]
